export const Data = [
  {
    id: "1",
    make: "Ford",
    model: "2020",
    price: "61,441",
    color: "Black",
    condition: "New",
  },
  {
    id: "2",
    make: "Tesla",
    model: "2018",
    price: "115,501",
    color: "Black",
    condition: "New",
  },
  {
    id: "3",
    make: "Honda",
    model: "2017",
    price: "75,945",
    color: "Green",
    condition: "Used",
  },
  {
    id: "4",
    make: "Ford",
    model: "2017",
    price: "180,526",
    color: "Blue",
    condition: "Used",
  },
  {
    id: "5",
    make: "Toyota",
    model: "2019",
    price: "142,175",
    color: "Green",
    condition: "Used",
  },
  {
    id: "6",
    make: "Toyota",
    model: "2017",
    price: "104,733",
    color: "Blue",
    condition: "New",
  },
  {
    id: "7",
    make: "Honda",
    model: "2020",
    price: "129,191",
    color: "White",
    condition: "Used",
  },
  {
    id: "8",
    make: "Ford",
    model: "2017",
    price: "92,884",
    color: "Red",
    condition: "New",
  },
  {
    id: "9",
    make: "Chevrolet",
    model: "2021",
    price: "135,109",
    color: "Blue",
    condition: "Used",
  },
  {
    id: "10",
    make: "Ford",
    model: "2017",
    price: "58,691",
    color: "Black",
    condition: "New",
  },
  {
    id: "11",
    make: "Chevrolet",
    model: "2021",
    price: "75,544",
    color: "Blue",
    condition: "New",
  },
  {
    id: "12",
    make: "Toyota",
    model: "2019",
    price: "147,249",
    color: "Green",
    condition: "New",
  },
  {
    id: "13",
    make: "Honda",
    model: "2017",
    price: "54,190",
    color: "Blue",
    condition: "New",
  },
  {
    id: "14",
    make: "Toyota",
    model: "2018",
    price: "52,808",
    color: "Green",
    condition: "Used",
  },
  {
    id: "15",
    make: "Chevrolet",
    model: "2020",
    price: "144,004",
    color: "Green",
    condition: "New",
  },
];
